### ISSUE TITLE
war vs. jar

### ISSUE THREAD

**Issue by carljmosca** [vaadin/trippy#1]
It seems to me that the trippy-ui project should be packaged as a jar and the trippy-starter should be a war...or I could be missing something.

**Comment by Legioth** [comment]
The purpose of the `trippy-starter` project is to include things that should really be part of an official Spring Boot starter for Vaadin Flow, as well as workarounds for some other features missing from Flow. By the time Flow 1.0.0 is stable, the `trippy-starter` module should thus not be needed any more.
