### ISSUE TITLE
map API Key required

### ISSUE THREAD

**Issue by carljmosca** [vaadin/trippy#2]
I believe a map API key is needed to make the trippy-ui work.

**Comment by Legioth** [comment]
Please get your own Maps API key at https://console.developers.google.com/ and add it to the `application.properties` with the name `map.apikey`.

We don't want to share an API key since it might cause unexpected behaviour if the quota for that key is depleted.

**Comment by carljmosca** [comment]
I was not suggesting you provide a key; just more information about the need so that folks could get it up and running slightly faster than I. :)

**Comment by Legioth** [comment]
Good point. I'll update the readme.
